baseURL = "https://snithish.netlify.com/"
languageCode = "en-us"
title = "Nithish's Ramblings"
theme = "coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Nithish Sankaranarayanan"
    description = "Nithish's personal blog"
    keywords = "blog,developer,personal,data engineering,databases,distributed systems"
    info = "A place to record my thoughts and learnings"
    footercontent = "Nothing here. Look up."

    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/snithish"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/snithish_"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/nithish-sankaranarayanan-0762b295/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"